[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.29"
evm_version = "cancun"
optimizer = true
optimizer_runs = 250
via_ir = true
auto_detect_remappings = false
remappings = [
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
kaia_mainnet = "${KAIA_RPC_URL}"
